import express from 'express';
import cors from 'cors';
import { env } from './config/env.js';
import routes from './routes/index.js';
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api', routes);
app.get('/health', (_req, res) => res.json({ status: 'ok' }));
if (process.env.NODE_ENV !== 'test') app.listen(env.port, () => console.log(`Server listening on ${env.port}`));
export default app;
